#!/bin/bash 
# 
# @author Zeus Intuivo <zeus@intuivo.com>
#


                          function load_bash_crm_cli() {
                            if [ ! -z ${BASHCRMCLI+x} ]; then   # check if a variable is set and not empty
                              {
                                . "$BASHCRMCLI/execute_command.sh" && THIS_SCRIPT_NAME=`basename "$0"`
                                heading Test
                              }
                            fi
                          }
load_bash_crm_cli

#echo "test 1 ">> ~/.zshrc
#: echo \"# PHPBrew  \" \>\> ~\/.zshrc
#echo "test 2 ">> ~/.zshrc
#: echo "# PHPBrew  " \>\> ~\/.zshrc
#echo "test 3 ">> ~/.zshrc
#: echo \"# PHPBrew  \" >> ~/.zshrc
#echo "test 3.1 ">> ~/.zshrc
#: echo \'# PHPBrew  \' >> ~/.zshrc
#echo "test 3.2 ">> ~/.zshrc
#: echo '# PHPBrew  ' >> ~/.zshrc

echo "test 4 ">> ~/.zshrc
: 'echo "# PHPBrew  " >> ~/.zshrc'
#echo "test 5 ">> ~/.zshrc
#: 'echo "# PHPBrew  " >> ~/.zshrc'
#echo "test 6 ">> ~/.zshrc
#: echo '"# PHPBrew  " >> ~/.zshrc'
#echo "test 7 ">> ~/.zshrc
#: echo '"# PHPBrew  "' >> ~/.zshrc

: echo "hola"
: echo \"hola\"
